# Generated by Django 4.2.23 on 2025-07-25 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated or corrected this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_time_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
