# Generated by Django 4.2.23 on 2025-07-28 22:27

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_add_number_days_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='number_days',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Manual input of number of days (excluding weekends)',
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
