# Generated by Django 4.2.23 on 2025-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_dailytimesummary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimesummary',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'On Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('not_scheduled', 'Not Yet Scheduled')], default='not_scheduled', max_length=20),
        ),
    ]
