# Generated by Django 4.2.23 on 2025-07-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_timeentry_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='event_time',
            field=models.DateTimeField(blank=True, help_text='The actual/corrected time of the event (if different from timestamp)', null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
