# Generated by Django 4.2.23 on 2025-07-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_timeentry_event_time_timeentry_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
