# Generated by Django 4.2.23 on 2025-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geofence_radius',
            field=models.IntegerField(default=100, help_text='Radius in meters for geofencing'),
        ),
    ]
