# Generated by Django 4.2.23 on 2025-07-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_location_geofence_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('management', 'Management'), ('it_support', 'IT Support')], default='employee', max_length=20),
        ),
    ]
