# Generated by Django 4.2.23 on 2025-07-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_timeentry_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
