# Generated by Django 4.2.23 on 2025-08-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_dailytimesummary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grace_period_minutes',
            field=models.IntegerField(default=5, help_text='Grace period in minutes before considering late (e.g., 5 minutes)'),
        ),
    ]
