# Generated by Django 4.2.23 on 2025-08-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_employee_grace_period_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='early_login_restriction_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Hours before scheduled time when early login is allowed (e.g., 1 hour)', max_digits=4),
        ),
    ]
