# Generated by Django 4.2.23 on 2025-07-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_timeentry_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the location', null=True),
        ),
    ]
