# Generated by Django 4.2.23 on 2025-07-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='break_threshold_minutes',
            field=models.IntegerField(default=30, help_text='Minimum break duration to be considered a break'),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_work_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Standard daily work hours before overtime', max_digits=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='lunch_break_minutes',
            field=models.IntegerField(default=60, help_text='Standard lunch break duration in minutes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours worked before overtime kicks in', max_digits=4),
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('regular', 'Regular Work'), ('overtime', 'Overtime'), ('break', 'Break'), ('lunch', 'Lunch Break')], default='regular', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_overtime', models.BooleanField(default=False)),
                ('is_break', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='geo.employee')),
                ('time_in_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions_as_in', to='geo.timeentry')),
                ('time_out_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions_as_out', to='geo.timeentry')),
            ],
            options={
                'verbose_name': 'Work Session',
                'verbose_name_plural': 'Work Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
