# Generated by Django 4.2.23 on 2025-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_employee_break_threshold_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='flexible_break_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Flexible break time included in total schedule', max_digits=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_schedule_hours',
            field=models.DecimalField(decimal_places=2, default=9.0, help_text='Total hours from time in to time out (including flexible break time)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_work_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Standard daily work hours before overtime (actual work time)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours worked before overtime kicks in (actual work time)', max_digits=4),
        ),
    ]
