# Generated by Django 4.2.23 on 2025-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_employee_early_login_restriction_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='require_schedule_compliance',
            field=models.BooleanField(default=True, help_text='Whether this employee must comply with scheduled times'),
        ),
    ]
