# Generated by Django 4.2.23 on 2025-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_employee_flexible_break_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Location accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude at time entry', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude at time entry', max_digits=11, null=True),
        ),
    ]
