# Generated by Django 4.2.23 on 2025-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_timeentry_accuracy_timeentry_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='min_accuracy_meters',
            field=models.IntegerField(default=100, help_text='Minimum required location accuracy in meters'),
        ),
    ]
