# Generated by Django 4.2.23 on 2025-07-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_overtimerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
